spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: test
    password: test

  security:
    user:
      name: TEST
      password: TEST
      roles: TEST