export const START_API_CHAIN = "START_API_CHAIN";
export const API_CHAIN_FINISHED_SUCCESSFULLY = "API_CHAIN_FINISHED_SUCCESSFULLY";
export const API_CHAIN_FINISHED_ERRONEOUSLY = "API_CHAIN_FINISHED_ERRONEOUSLY";
