export const API_CHAIN_STARTED = "API_CHAIN_STARTED";
export const API_CHAIN_FINISHED_SUCCESSFULLY = "API_CHAIN_FINISHED_SUCCESSFULLY";
export const API_CHAIN_FINISHED_ERRONEOUSLY = "API_CHAIN_FINISHED_ERRONEOUSLY";