export const EMPLOYEE_LIST_UPDATE_ALL = 'EMPLOYEE_LIST_UPDATE_ALL';
export const EMPLOYEE_LIST_UPDATE_SINGLE_SALARY = 'EMPLOYEE_LIST_UPDATE_SINGLE_SALARY';
export const EMPLOYEE_LIST_UPDATE_SINGLE = 'EMPLOYEE_LIST_UPDATE_SINGLE';
