export const EMPLOYEE_FORM_UPDATE_NAME = "EMPLOYEE_FORM_UPDATE_NAME";
export const EMPLOYEE_FORM_UPDATE_SALARY = "EMPLOYEE_FORM_UPDATE_SALARY";
export const EMPLOYEE_FORM_CLEAR = "EMPLOYEE_FORM_CLEAR";