spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_SCHEMA:clientserverdemo}?createDatabaseIfNotExist=true&serverTimezone=Europe/Moscow
    username: ${DATABASE_UNAME:root}
    password: ${DATABASE_PWD:ip1k5PNCgjHbmK}

  liquibase:
    change-log: classpath:db/changelog/master.xml

  security:
    user:
      name: ${SECURITY_UNAME:USER}
      password: ${SECURITY_PWD:USER}
      roles: ${SECURITY_ROLE:USER}

server:
  port: ${SERVER_PORT:12121}